### ISSUE TITLE
Missing icons - Arch Linux - OpenSuse

### ISSUE THREAD

**Issue by RaphaelRochet** [lucasdiedrich/gnome-display-switcher#1]
Hi,
I do not have the pretty icons like your screenshot. (Installed from ego)
Is there something more to do to install ?
Edit : gnome-shell 3.18.2 / Arch Linux

**Comment by lucasdiedrich** [comment]
Hi Raphael, 

The extension is packed with everything needed, only thing that should be installed is xrandr which is default on most linux dists. I didn't understand what you said with 'ego', its from installation script or Gnome's Extension website?

I'm testing over differents dist and seems ok. Looking for the problem.

**Comment by RaphaelRochet** [comment]
Hi,
ego stands for extensions.gnome.org 
The svg icons are in the icons folder, but not used. I see 4 times the same picture (looks like 'display' or 'video-display' icon)

Did you explicitly add your icons subfolder to the Gtk icon theme ?
In my last extension I had to do this to get it work :
```
Gtk.IconTheme.get_default().append_search_path(Me.dir.get_child('icons').get_path());
```
( https://github.com/RaphaelRochet/arch-update )

**Comment by lucasdiedrich** [comment]
Raphael, actually i do something similar over Utils.js class (function initTheme), i changed that to something similar to yours now, and padronized files permissions. Already uploaded version 0.5 to EGO, i'm just waiting someone to aprove.

Thanks.

**Comment by RaphaelRochet** [comment]
I upgraded from ego, and unfortunately it's not fixed : on my two computers it's the same icon used for all modes.
![capture du 2016-01-24 23-24-35](https://cloud.githubusercontent.com/assets/1675389/12539408/d7638e04-c2f1-11e5-902a-ded70d77299f.png)

I tried disabling all another extensions, but no luck.

**Comment by lucasdiedrich** [comment]
Raphael, this icons are from Adwait theme, named video-display.png, which i don't use and don't call anywhere in the code, just an creepy behavior i think, unfortunetly i can't reproduce this behavior over Fedora 23 with Gnome shell 3.18.3.

I'm thinking that could be something related to packaging inside de zip file, can you try installing this using manual installation?

**Comment by RaphaelRochet** [comment]
Okay I will clone the git repo and try

**Comment by RaphaelRochet** [comment]
Too bad, still the same. (And you're right I use the Adwaita theme, the default theme on Arch Linux. )

**Comment by lucasdiedrich** [comment]
[My feeling right now:](https://cloud.githubusercontent.com/assets/817482/12539920/349eb160-c2e4-11e5-9606-2fbd16f7429d.jpg)

Raphael, thanks for the response, i'll keep searching for any flaws in the code.

**Comment by lucasdiedrich** [comment]
Reproduced the bug over Antergos Distro ( Arch Based ). 

Going to test over Opensuse LEAP and Ubuntu Gnome now.

**Comment by lucasdiedrich** [comment]
**Update**

I was trying to debug this over open-suse and antergos, it seems that the function works, at least it is appending the icons folder to the path, but for some reason gnome-shell is not searching finding by the icons names.

> log(theme.get_search_path());
`Gjs-Message: JS LOG: /home/test/.local/share/icons,/home/test/.icons,/usr/share/icons,/usr/share/pixmaps`
> Theme.append_search_path(Local.dir.get_child('icons').get_path());
> log(theme.get_search_path());
`Gjs-Message: JS LOG: /home/test/.local/share/icons,/home/test/.icons,/usr/share/icons,/usr/share/pixmaps,/home/test/.local/share/gnome-shell/extensions/display-switcher@lucas.diedrich.gmail.com/icons `
> log(theme.has_icon('display-mirrored'));
`Gjs-Message: JS LOG: false`

**Comment by RaphaelRochet** [comment]
It has something to do with the prefix 'display-' which may have a special meaning. Renamed with another and it works : 

![capture du 2016-01-26 09-00-37](https://cloud.githubusercontent.com/assets/1675389/12575274/8f2a7164-c40b-11e5-864d-fb422000953f.png)

I guess you should probably try to prefix your icons with something unique to your extension !

**Comment by lucasdiedrich** [comment]
Raphael, i've tested changing the icons name and it works both Antergos Linux and Opensuse now. Already submitted the new package to EGO.

Thanks for your help.

**Comment by RaphaelRochet** [comment]
Thanks ;)
Sorry I did not answer because comment edit are not sent by email !
Works nice

**Comment by lucasdiedrich** [comment]
Don't worry, i've tested over Opensuse and Arch Linux before closing, thanks for your help!
