### ISSUE TITLE
[enhancement] Clicking on panel icon should trigger switcher

### ISSUE THREAD

**Issue by mlda065** [lucasdiedrich/gnome-display-switcher#13]
I'd like it so that if you click on the icon on the panel, then the switcher appears, just like if you pressed the keyboard shortcut.
I often can't remember keyboard shortcuts, so clicking the icon is a simple and intuitive alternative.

I looked at the code to try to do this myself, but I'm a bit lost.
I figured out how to make the icon do something when clicked, but I haven't been able to figure out what function to call so that the _something_ it does when clicked is the same as what the keyboard shortcut does.

The following should be inserted between lines 100 and 101 of `extension.js`.

```
this._topIcon.connect('button-release-event',   function () {
    // function call for popup goes here
});
```

I suspect the code that should go in the middle there should be `this._switcherManager._show()` or `DisplayExtension._show()`.
Either way, I have no idea what arguments to give those functions.

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
