### ISSUE TITLE
doesn't work on iMac

### ISSUE THREAD

**Issue by maxwellzdeamon** [lucasdiedrich/gnome-display-switcher#14]
can you help me troubleshoot?  I have fedora 24 installed on an iMac (late 2012) & x1 carbon; they are connected via hdmi.  When I use the gnome-display-switcher nothing happens on either.

Jeremy

**Comment by lucasdiedrich** [comment]
@maxwellzdeamon, sorry for the late response, can you paste here the result of the following code: 

_$ xrandr_

and

_$ ps aux | grep gnome-shell_

Thanks.

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
