### ISSUE TITLE
no longer works - nothing happens when keybinding pressed

### ISSUE THREAD

**Issue by mlda065** [lucasdiedrich/gnome-display-switcher#17]
Since late late year I haven't been able to get this to work.

# Steps to reproduce

* Ubuntu 17.10
* Gnome 3.26.2
* Install the extension through the Tweak tool
* press `super`+`I`
* change extension setting to something else, e.g. `ctrl`+`alt`+`I`
* press `ctrl`+`alt`+`I`
* enable `Running icon` in extension settings

# Expected behaviour

* When I press `super`+`I`  the extension's display switcher appears
* When I change the keybinding and press that  the extension's display switcher appears
* An icon for this extension appears somewhere

# Actual Behaviour

* When I press the `super` + `I` nothing happens.
* When I change the keybinding and press that  nothing happens
* no icon appears anywhere for this extension

# Notes

I'm creating a seperate issue to #16 because despite being cause by this version of GNOME, my failure mode is different.

This has been happening since late last year.

I've tried uninstalling and reinstalling the extension.

The fact that I get the same result with a non-default binding suggests that it's not a binding clash.

Where is the icon supposed to appear? Even back when the extension worked for me, I never saw the icon.

I don't know how to find out what version of the extension I'm running.

**Comment by mlda065** [comment]
Ah yes that does work. I did not know that.

Thanks

**Comment by lucasdiedrich** [comment]
Thanks for the response, for some creepy reason gnome doesn't publish that.

Em seg, 18 de jun de 2018 às 08:03, Matthew Davis <notifications@github.com>
escreveu:
