### ISSUE TITLE
Add an GUI for changing options

### ISSUE THREAD

**Issue by RaphaelRochet** [lucasdiedrich/gnome-display-switcher#2]
A tiny option dialog where we can easily change the shortcut could be a nice enhancement :)
Or maybe integrate with Gnome's keyboard settings (if possible at all).

**Comment by lucasdiedrich** [comment]
Raphael, this is already on progress, i'm making an selector over prefs.js (Default extension settings).

**Comment by lucasdiedrich** [comment]
Going livre tomorrow, i'm having issues with Gnome icons again.

**Comment by lucasdiedrich** [comment]
Just uploaded the final zip to EGO, https://extensions.gnome.org/review/5583.

**Comment by RaphaelRochet** [comment]
Nice :+1:
