### ISSUE TITLE
make selection of profiles editable/allow to save custom profiles

### ISSUE THREAD

**Issue by corebots** [lucasdiedrich/gnome-display-switcher#5]
the menu shown could be extended with custom profiles saved by the user. a similar feature has been provided through an older extension: https://github.com/bodedejavu/gnome-shell-extensions but it seems abandoned now and doesn't work with latest gnome anymore. perhaps you could re-implement a similar feature in your extension? or even re-use the code? This could help users with more than two monitors(like myself) to chose between several commonly used configuration and at the same time would be a solution for your currently available profiles to remember the left-right desktop-extend direction.

**Comment by lucasdiedrich** [comment]
Corebots, thats an great idea and is already planned for this project, but
at this time i'm focusing on make the extension works great for all users.
As soon as i get time i'll start creating the profiles stuff over
display-switcher.

Thanks for the idea, this is awesome.


Em qua, 17 de fev de 2016 às 15:18, corebots <notifications@github.com>
escreveu:

**Comment by mattia-b89** [comment]
+1

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
