### ISSUE TITLE
Add a button to open display settings

### ISSUE THREAD

**Issue by dsboger** [lucasdiedrich/gnome-display-switcher#7]
Is that possible?

**Comment by lucasdiedrich** [comment]
Yes totally, probably a shortcut on the top menu icon, what do you think?

Another idea its to bind another key, for example, when we press '<super> + I' it shows the popup menu, than we press 's' to open settings. 

Thanks.

**Comment by dsboger** [comment]
I was thinking of a fifth button to the right of the display options, maybe after a separator.

I don't use the top bar icon. Thinking about it, it would be nice if the whole thing were integrated with the system menu. But that is matter for another feature request. :)

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
