### ISSUE TITLE
Auto-select audio-source

### ISSUE THREAD

**Issue by lucasdiedrich** [lucasdiedrich/gnome-display-switcher#9]
The extension should be able to auto-select the sound board when changing the video-display.

> Ex: When selecting "secondary-only" and the secondary display driver is an "HDMI" device, it should set the HDMI as an audio output. The reverse thing shoud be done when the HDMI cable is disconnected.

This should apply to all digital output.

**Comment by logos88** [comment]
This would make this extension completely awesome. Hope it will arrive some day : )

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
